services:
  wavesnode:
    image: unitsnetwork/consensus-client:main
    pull_policy: never
    environment:
      JAVA_OPTS: -Dlogback.file.level=TRACE
      WAVES_LOG_LEVEL: TRACE
      WAVES_HEAP_SIZE: 2g
      # NODE_NUMBER:
      # WAVES_WALLET_SEED:
    volumes:
      - ./:/etc/waves:ro
      - ../ec-common:/etc/secrets:ro
