name: l2
include:
  - ./configs/blockscout/blockscout.yml
services:
  ec-1:
    container_name: ec-1
    hostname: ec-1
    # extends:
    #   file: ./configs/besu/besu.yml
    #   service: besu
    # ports:
    #   - "127.0.0.1:18551:8551" # Engine port - doesn't have all APIs
    #   - "127.0.0.1:18545:8545" # RPC port, for Metamask e.g.
    #   - "127.0.0.1:18546:8546" # WebSocket
    # volumes:
    #   - ./configs/ec-common/p2p-key-1.hex:/etc/secrets/p2p-key:ro
    #   - ./logs/ec-1:/opt/besu/logs
    extends:
      file: ./configs/op-geth/op-geth.yml
      service: op-geth
    ports:
      - "127.0.0.1:18551:8551" # Engine port
      - "127.0.0.1:18545:8545" # RPC port
    volumes:
      - ./configs/ec-common/p2p-key-1.hex:/etc/secrets/p2p-key:ro
      - ./configs/ec-common/jwt-secret-1.hex:/etc/secrets/jwtsecret:ro
      - ./logs/ec-1:/root/logs

  ec-2:
    container_name: ec-2
    hostname: ec-2
    extends:
      file: ./configs/op-geth/op-geth.yml
      service: op-geth
    ports:
      - "127.0.0.1:28551:8551" # Engine port
      - "127.0.0.1:28545:8545" # RPC port
    volumes:
      - ./configs/ec-common/p2p-key-2.hex:/etc/secrets/p2p-key:ro
      - ./configs/ec-common/jwt-secret-2.hex:/etc/secrets/jwtsecret:ro
      - ./logs/ec-2:/root/logs

  wavesnode-1:
    container_name: wavesnode-1
    hostname: wavesnode-1
    extends:
      file: ./configs/wavesnode/wavesnode.yml
      service: wavesnode
    image: ${WAVES_NODE_IMAGE_1:-${WAVES_NODE_IMAGE:-consensus-client:local}}
    ports:
      - "127.0.0.1:16869:6869"
    environment:
      NODE_NUMBER: 1
      WAVES_WALLET_SEED: HnyGuCEnV1A # devnet-1, addr: 3FNraPMYcfuGREcxorNSEBHgNLjmYtaHy9e
    volumes:
      - ./logs/wavesnode-1:/var/log/waves
    depends_on:
      ec-1:
        condition: service_healthy
      update-genesis:
        condition: service_completed_successfully

  wavesnode-2:
    container_name: wavesnode-2
    hostname: wavesnode-2
    extends:
      file: ./configs/wavesnode/wavesnode.yml
      service: wavesnode
    image: ${WAVES_NODE_IMAGE_2:-${WAVES_NODE_IMAGE:-consensus-client:local}}
    ports:
      - "127.0.0.1:26869:6869"
    environment:
      NODE_NUMBER: 2
      WAVES_WALLET_SEED: HnyGuCEnV1B # devnet-2, addr: 3FSrRN8X7cDsLyYTScS8Yf8KSwZgJBwf1jU
    volumes:
      - ./logs/wavesnode-2:/var/log/waves
    depends_on:
      ec-2:
        condition: service_healthy
      update-genesis:
        condition: service_completed_successfully

  update-genesis:
    container_name: update-genesis
    image: ${WAVES_NODE_IMAGE:-ghcr.io/wavesplatform/waves:test-gengen}
    volumes:
      - ./configs/wavesnode:/tmp/configs
    command:
      - gengen
      - /tmp/configs/genesis-template.conf
      - /tmp/configs/genesis.conf

  deploy:
    container_name: deploy
    hostname: deploy
    extends:
      file: ./deploy/deploy.yml
      service: deploy
    environment:
      MAIN: deploy.py
    volumes:
      - ./logs/deploy:/var/log/deploy
    depends_on:
      wavesnode-1:
        condition: service_healthy
      ec-1:
        condition: service_healthy

  tests:
    container_name: tests
    hostname: tests
    extends:
      file: ./deploy/deploy.yml
      service: deploy
    environment:
      MAIN: tests.py
    volumes:
      - ./logs/tests:/var/log/deploy
    depends_on:
      deploy:
        condition: service_completed_successfully
    profiles: [ tests ]
