name: l2
include:
  - ./configs/blockscout/${BS-enabled}.yml
services:
  ec-1:
    container_name: ec-1
    hostname: ec-1
    extends:
      file: ./configs/besu/besu.yml
      service: besu
    ports:
      - "127.0.0.1:18551:8551" # Engine port - doesn't have all APIs
      - "127.0.0.1:18545:8545" # RPC port, for Metamask e.g.
      - "127.0.0.1:18546:8546" # WebSocket
    volumes:
      - ./configs/ec-common/p2p-key-1.hex:/etc/secrets/p2p-key:ro
      - ./logs/ec-1:/opt/besu/logs

  ec-2:
    container_name: ec-2
    hostname: ec-2
    extends:
      file: ./configs/geth/geth.yml
      service: geth
    ports:
      - "127.0.0.1:28551:8551" # Engine port
      - "127.0.0.1:28545:8545" # RPC port, useful because doesn't require an auth token
    volumes:
      - ./configs/ec-common/p2p-key-2.hex:/etc/secrets/p2p-key:ro
      - ./configs/ec-common/jwt-secret-2.hex:/etc/secrets/jwtsecret:ro
      - ./logs/ec-2:/root/logs

  wavesnode-1:
    container_name: wavesnode-1
    hostname: wavesnode-1
    extends:
      file: ./configs/wavesnode/wavesnode.yml
      service: wavesnode
    image: unitsnetwork/consensus-client:${WAVES_NODE_1_TAG:-main}
    ports:
      - "127.0.0.1:16869:6869"
    environment:
      NODE_NUMBER: 1
      WAVES_WALLET_SEED: HnyGuCEnV1A # devnet-1, addr: 3FNraPMYcfuGREcxorNSEBHgNLjmYtaHy9e
    volumes:
      - ./logs/wavesnode-1:/var/log/waves
    depends_on:
      ec-1:
        condition: service_healthy

  wavesnode-2:
    container_name: wavesnode-2
    hostname: wavesnode-2
    extends:
      file: ./configs/wavesnode/wavesnode.yml
      service: wavesnode
    image: unitsnetwork/consensus-client:${WAVES_NODE_2_TAG:-main}
    ports:
      - "127.0.0.1:26869:6869"
    environment:
      NODE_NUMBER: 2
      WAVES_WALLET_SEED: HnyGuCEnV1B # devnet-2, addr: 3FSrRN8X7cDsLyYTScS8Yf8KSwZgJBwf1jU
    volumes:
      - ./logs/wavesnode-2:/var/log/waves
    depends_on:
      ec-2:
        condition: service_healthy

  deploy:
    container_name: deploy
    build:
      context: ./deploy/
      network: host
    restart: no # Manual start
    platform: linux/amd64 # HACK for Apple Silicon
    environment:
      DEPLOY_LOG_DIR: /home/node/logs
    volumes:
      - ./deploy:/usr/src/app
      # - ./logs/deploy:/home/node/logs
    depends_on:
      wavesnode-1:
        condition: service_healthy
      ec-1:
        condition: service_healthy
