services:
  besu:
    image: hyperledger/besu:latest # Debug version: besu-debug:latest , see _debug/
    volumes:
      - ../ec-common/genesis.json:/genesis.json:ro
      - .:/config:ro
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log4j2.xml
    command:
      - --config-file=/config/besu.conf
