services:
  besu:
    image: hyperledger/besu:latest
    volumes:
      - ../ec-common/genesis.json:/genesis.json:ro
      - .:/config:ro
      - ./run-besu.sh:/tmp/run.sh:ro
    env_file:
      - ../ec-common/peers.env
    environment:
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    entrypoint: /tmp/run.sh
