services:
  geth:
    extends:
      file: ./services/geth.yml
      service: geth
  waves-node:
    extends:
      file: ./services/waves-node.yml
      service: waves-node
    environment:
      EXECUTION_CLIENT: geth
