services:
  geth:
    image: ethereum/client-go:stable
    stop_grace_period: 30s
    entrypoint: /tmp/run.sh
    volumes:
      - ./run.sh:/tmp/run.sh
      - ../ec-common/genesis.json:/tmp/genesis.json:ro
    healthcheck:
      test: 'wget -qO /dev/null --header "content-type: application/json" --post-data {\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1} http://127.0.0.1:8545'
      interval: 5s
      timeout: 1s
      retries: 10
