[profile.default]
solc-version = "0.8.26"
src = "src"
out = "target"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    'forge-std/=lib/forge-std/src',
    'safe-contracts/=lib/safe-contracts/contracts'
]
