services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.6
    stop_grace_period: 10s
    entrypoint: /tmp/run.sh
    volumes:
      - ../ec-common:/etc/secrets:ro
      - ./run-op-geth.sh:/tmp/run.sh:ro
    env_file:
      - ../ec-common/peers.env
    healthcheck:
      test: 'wget -qO /dev/null --header "content-type: application/json" --post-data {\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1} http://127.0.0.1:8545'
      interval: 5s
      timeout: 1s
      retries: 10
