services:
  stats-db-init:
    container_name: stats-db-init
    image: postgres:15
    volumes:
      - ../../../data/stats-db:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  stats-db:
    container_name: stats-db
    hostname: stats-db
    image: postgres:15
#    user: 2000:2000
    shm_size: 128m
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_DB: 'stats'
        POSTGRES_USER: 'stats'
        POSTGRES_PASSWORD: 'n0uejXPl61ci6ldCuE2gQU5Y'
    volumes:
      - ../../../data/stats-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  stats:
    container_name: stats
    hostname: stats
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    platform: linux/amd64
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./stats.env
    environment: # TODO two databases
      - STATS__DB_URL=postgres://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-db:5432/stats
      - STATS__BLOCKSCOUT_DB_URL=${STATS__BLOCKSCOUT_DB_URL:-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true
