services:
  backend:
    container_name: bs-backend
    image: ghcr.io/blockscout/blockscout:${BLOCKSCOUT_DOCKER_TAG:-latest}
    restart: always
    stop_grace_period: 20s
    command: |
      sh -c '
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && \
        bin/blockscout start'
    env_file:
      -  ./bs-backend.env
    volumes:
      - ../../../logs/bs-backend/:/app/logs/prod
      - ./:/assets:ro
    depends_on:
      ec-1:
        condition: service_healthy
