services:
  nginx:
    container_name: nginx
    image: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './templates:/etc/nginx/templates'
      - '../../../logs/nginx:/var/log/nginx'
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://bs-backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://bs-frontend:3000}
      EC_RPC_PROXY_PASS: ${EC_RPC_PROXY_PASS:-http://ec-1:8545}
      EC_WS_PROXY_PASS: ${EC_WS_PROXY_PASS:-http://ec-1:8546}
      WAVES_PROXY_PASS: ${WAVES_PROXY_PASS:-http://waves-node-1:6869}
    ports:
      - '127.0.0.1:3000:3000'
      - '127.0.0.1:3001:3001'
      - '127.0.0.1:3002:3002'
      - '127.0.0.1:10001:10001'
