services:
  deploy:
    build:
      context: .
      network: host
    restart: no # Manual start
    platform: linux/amd64 # HACK for Apple Silicon
    environment:
      LOGGING_CONFIG: /usr/src/app/logging.conf
    volumes:
      - .:/usr/src/app
      - ../../contracts/eth:/tmp/contracts
