services:
  besu:
    container_name: besu
    image: hyperledger/besu:latest
    pull_policy: always
    stop_grace_period: 5m
    command:
      - --logging=ALL
      - --host-allowlist=*
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL,TRACE,ADMIN
      - --rpc-http-cors-origins=all
      - --rpc-ws-enabled
      - --discovery-dns-url=enrtree://AIRIZFFZSCSIVHXTKA44WYZQJMR75FLTGWJ5TUNEW5IP7QKZDLBRK@${NETWORK}-nodes.unit0.dev
      - --engine-rpc-enabled
      - --engine-jwt-secret=/etc/secrets/jwtsecret
      - --engine-host-allowlist=*
      - --node-private-key-file=/etc/secrets/p2p-key
      - --data-path=/var/lib/besu
      - --genesis-file=/etc/besu/genesis.json
      - --data-storage-format=BONSAI
      - --discovery-enabled=true
      - --network-id=${NETWORK_ID}
    volumes:
      - ../genesis-${NETWORK}.json:/etc/besu/genesis.json
      - ../data/secrets:/etc/secrets:ro
      - ../log4j2.xml:/etc/besu/log4j2.xml
      - ../data/besu:/var/lib/besu
      - ../logs/besu:/opt/besu/logs
    ports:
      - '30303:30303/tcp'
      - '30303:30303/udp'
      - '8545:8545'
    environment:
      - LOG4J_CONFIGURATION_FILE=/etc/besu/log4j2.xml
