services:
  waves-node:
    container_name: waves-node
    image: ghcr.io/unitsnetwork/consensus-client:testnet
    stop_grace_period: 5m
    ports:
      - "6869:6869"
      - "6868:6868"
      - "6865:6865"
    environment:
      - JAVA_OPTS=-Dwaves.config.directory=/etc/waves -Dlogback.file.level=TRACE -Dwaves.blockchain.type=$NETWORK
    env_file:
      - path: ../secrets.env
        required: false
    volumes:
      - ../data/secrets:/etc/secrets:ro
      - ../data/waves:/var/lib/waves/data
      - ../waves-${NETWORK}.conf:/etc/waves/waves.conf:ro
      - ../logback.xml:/etc/waves/logback.xml
      - ../logs/waves:/var/log/waves
